import Booking from "../models/BookingSchema.js";
import User from "../models/UserSchema.js";
import Doctor from "../models/DoctorSchema.js";

export const updateUser = async (req, res) => {
  const email = req.params.id;
  console.log("ðŸš€ ~ updateUser ~ email:", email)
  console.log("ðŸš€ ~ updateUser ~ body:", req.body)

  try {
    const updatedUser = await User.findOneAndUpdate(
      { email: email },
      { $set: req.body },
      // { new: true }
    ).select('-password');
    console.log("ðŸš€ ~ updateUser ~ updatedUser:", updatedUser)

    res.status(200).json({
      success: true,
      message: "Successfully updated",
      data: updatedUser,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to update!",
      error: error.message,
    });
  }
};

export const deleteUser = async (req, res) => {
  const id = req.params.id;

  try {
    await User.findByIdAndDelete(id);

    res.status(200).json({
      success: true,
      message: "Successfully deleted",
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to delete!",
      error: error.message,
    });
  }
};

export const getSingleUser = async (req, res) => {
  const id = req.params.id;

  try {
    const user = await User.findById(id).select("-password"); // Query the user by ID

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "No User Found!",
      });
    }

    res.status(200).json({
      success: true,
      message: "User Found",
      data: user,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to retrieve user!",
      error: error.message,
    });
  }
};

export const getAllUser = async (req, res) => {
  try {
    const users = await User.find().select("-password");

    res.status(200).json({
      success: true,
      message: "Users Found",
      data: users,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to retrieve users!",
      error: error.message, // Corrected error handling
    });
  }
};

export const getUserProfile = async (req, res) => {
  const userId = req.userId
  try {
    const user = await User.findById(userId);

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "No User Found!",
      });
    }

    const { password, ...rest } = user._doc

    return res.status(200).json({ success: true, message: 'Profile info is getting', data: { ...rest } });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Failed to retrieve user!",
      data: error,
    });
  }
};

export const getMyAppointments = async (req, res) => {
  try {
    // step -1 : retrieve appointments from booking for specific user
    const bookings = await Booking.find({ user: req.userId });
    // step -2 : extract doctor ids from appointment bookings
    const doctorIds = bookings - map(el => el.doctor.id);
    // step - 3 : retrieve doctors using doctor ids
    const doctors = await Doctor.find({ _id: { $in: doctorIds } }).select('-password');

    res.status(200).Json({ success: true, message: 'Appointments are getting', data: doctors });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Something went wrong, cannot get",
      data: error,
    });
  }
};
